services:
  endee:
    image: endeeio/endee-server:latest
    container_name: endee-server
    ports:
      - "8080:8080"
    volumes:
      - endee-data:/data
    environment:
      - NDD_AUTH_TOKEN=
    restart: unless-stopped

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - endee
    env_file:
      - .env
    environment:
      - ENDEE_TOKEN=${ENDEE_TOKEN:-}
      - ENDEE_BASE_URL=http://endee:8080/api/v1

volumes:
  endee-data:
